[build]
  publish = "build/web"
  command = "flutter pub get && flutter build web --release --web-renderer canvaskit"

[build.environment]
  FLUTTER_VERSION = "3.24.0"
  NODE_VERSION = "20.18.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.deploy-preview]
  command = "flutter pub get && flutter build web --release --web-renderer canvaskit"

[context.branch-deploy]
  command = "flutter pub get && flutter build web --release --web-renderer canvaskit"