# netlify.toml

[build]
  publish = "build/web"
  command = """
    curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz \
    && tar xf flutter_linux_3.24.0-stable.tar.xz \
    && export PATH="$PATH:$(pwd)/flutter/bin" \
    && flutter pub get \
    && flutter build web --release --web-renderer canvaskit
  """

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.deploy-preview]
  command = """
    curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz \
    && tar xf flutter_linux_3.24.0-stable.tar.xz \
    && export PATH="$PATH:$(pwd)/flutter/bin" \
    && flutter pub get \
    && flutter build web --release --web-renderer canvaskit
  """

[context.branch-deploy]
  command = """
    curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz \
    && tar xf flutter_linux_3.24.0-stable.tar.xz \
    && export PATH="$PATH:$(pwd)/flutter/bin" \
    && flutter pub get \
    && flutter build web --release --web-renderer canvaskit
  """
